### TensorFlow 簡介
- 最初由 Google Brain Team 所開發
- Apache 2.0 open source license 開放原始碼規範
- 設計目的: 使矩陣運算達到最高效能，並且能跨平台執行
- TensorFlow 由 tensor (代表張量運算) 與 flow (代表資料處理流程) 所組成
- TensorFlow 透過先建立好的 "計算圖" 來執行: 節點(Node)代表運算、邊(Edge)代表張量的資料流  

### TensorFlow 的架構
- 高階 API: Keras、TF-Learn、TF-Slim、TF-Layer
- 前端程式語言: Python、C++
- 分散式執行引擎 (tensorflow distributed execution engine)
- 平台: Windows、Linux、Android、iOS、Raspberry Pi
- 處理器: CPU、GPU、TPU

### TensorFlow 程式設計的流程
#### 1. 建立計算圖

方法一: 數值設定在本階段完成

- 建立 tensorflow 常數

      ts_c = tf.constant(常數值, name = 常數名稱)
      
      [註]儲存的型態: tf.Tensor (TensorFlow 張量)、shape() (0 維張量)、dtype=int32 (張量資料型態)

- 建立 tensorflow 變數

      ts_x = tf.Variable(變數值, name = 變數名稱)

方法二: 數值設定在 "執行計算圖" 的階段完成 - placeholder

Ex:

      a = tf.placeholder("int32")
      b = tf.placeholder("int32")
      c = tf.multiply(a, b)

#### 2. 執行計算圖

方法一: 使用 tf.Session()/sess.close() 來開啟/關閉 Session

- 建立 session (代表在用戶端與執行裝置之間建立連結)

      sess = tf.Session()

- 初始化所有 tensorflow global 變數

      init = tf.global_variables_initializer()
      sess.run(init)

- 執行 tensorflow 計算圖的方法

      1. sess.run(常數/變數)
      [註] placeholder 的方法: sess.run(c , feed_dict = {a: 數值, b: 數值}) 
      
      2. .eval(session = sess)
    
- 關閉 session

      sess.close()

方法二: 使用 with 語法開啟和自動關閉 Session

      with tf.Session() as sess:
          (初始化所有 tensorflow global 變數)
          init = tf.global_variables_initializer()
          sess.run(init)
          
          (執行 tensorflow 計算圖)
          1. sess.run(常數/變數)
          [註] placeholder 的方法: sess.run(c , feed_dict = {a: 數值, b: 數值}) 
      
          2. .eval()

### TensorFlow 常用的基本數值運算
- 加法: tf.add(x, y, name = None)
- 減法: tf.subtract(x, y, name = None)
- 乘法: tf.multiply(x, y, name = None)
- 除法: tf.divide(x, y, name = None)
- 餘數: tf.mod(x, y, name = None)
- 平方: tf.sqrt(x, name = None)
- 絕對值: tf.abs(x, name = None)

### TensorBoard: 以視覺化的方式查看所建立的計算圖
#### 1. 建立 TensorFlow 變數 (name 參數設定的名稱會顯示在 TensorBoard 上)

#### 2. 將要顯示在 TensorBoard 的資料寫入 log 檔

- tf.summary.merge_all(): 將要顯示在 TensorBoard 的資料整合。

- tf.summary.FileWriter('子目錄', sess.graph): 將要顯示在 TensorBoard 的資料寫入 log 檔。log 檔會儲存在目前程式執行目錄下的子目錄。

- 啟動 tensorboard (Windows)

      (1) 確認 log 目錄檔案是否產生
      
      (2) 啟用 tensorflow 的 anaconda 虛擬環境
      
      (3) 啟動 tensorboard: tensorboard --logdir=log檔的路徑
      
      (4) 在 tensorboard 查看計算圖: 輸入 http://localhost:本機位址/，再點選 GRAPHS


### 使用 TensorFlow 建立張量與矩陣運算

In [1]:
import tensorflow as tf
import numpy as np

#### 1. 建立 1 維、2 維張量

In [3]:
# 建立一維張量
ts_A = tf.Variable([0.1, 0.2, 0.3])

with tf.Session() as sess:
    # 初始化所有 tensorflow global 變數
    init = tf.global_variables_initializer()
    sess.run(init)
    
    A = sess.run(ts_A)
    print('A=' + str(A))
    
print('---------------')
# 查看一維張量形狀
print('A.shape =' + str(A.shape)) 
print('---------------')
# 建立二維張量
ts_B = tf.Variable([[0.1, 0.2, 0.3],[0.6, 0.5, 0.4]])

with tf.Session() as sess:
    # 初始化所有 tensorflow global 變數
    init = tf.global_variables_initializer()
    sess.run(init)
    
    B = sess.run(ts_B)
    print('B=')
    print(B)
    
# 查看二維張量形狀
print('---------------')
print('B.shape =' + str(B.shape))

A=[0.1 0.2 0.3]
---------------
A.shape =(3,)
---------------
B=
[[0.1 0.2 0.3]
 [0.6 0.5 0.4]]
---------------
B.shape =(2, 3)


#### 2. 矩陣基本運算

In [4]:
# 建立計算圖 (二維張量)
X = tf.Variable([[0.4, 0.1, 0.3]])

W = tf.Variable([[-0.1, 0.1],
                 [0.3, -0.2],
                 [0.1, 0.3]])

b = tf.Variable([[0.2, 0.1]])

# 矩陣相乘: tf.matmul
XW = tf.matmul(X, W)

Sum = XW + b

# 執行計算圖
with tf.Session() as sess:
    # 初始化所有 tensorflow global 變數
    init = tf.global_variables_initializer()
    sess.run(init)
    
    print('XW=')
    print(sess.run(XW))
    print('---------------')
    print('Sum=')
    print(sess.run(Sum))

XW=
[[0.02       0.11000001]]
---------------
Sum=
[[0.22       0.21000001]]


### 使用 TensorFlow 進行類神經網路運算

#### 1. 給定輸入值、權重和偏權值

In [5]:
# 建立計算圖 (二維張量)
X = tf.Variable([[0.4, 0.1, 0.3]])

W = tf.Variable([[-0.1, 0.1],
                 [0.3, -0.2],
                 [0.1, 0.3]])

b = tf.Variable([[0.2, 0.1]])

# 矩陣相乘: tf.matmul
XW = tf.matmul(X, W)

Sum = XW + b

# 活化函數為 relu function
#y = tf.nn.relu(Sum)

# 活化函數為 sigmoid function
y = tf.nn.sigmoid(Sum)

# 執行計算圖
with tf.Session() as sess:
    # 初始化所有 tensorflow global 變數
    init = tf.global_variables_initializer()
    sess.run(init)
    
    print('XW=')
    print(sess.run(XW))
    print('---------------')
    print('Sum=')
    print(sess.run(Sum))
    print('---------------')
    print('y=')
    print(sess.run(y))

XW=
[[0.02       0.11000001]]
---------------
Sum=
[[0.22       0.21000001]]
---------------
y=
[[0.55477923 0.5523079 ]]


#### 2. 給定輸入值，權重與偏權值以常態分佈的亂數初始化

In [6]:
# 建立計算圖 (二維張量)
X = tf.Variable([[0.4, 0.1, 0.3]])

W = tf.Variable(tf.random_normal([3, 2]))

b = tf.Variable(tf.random_normal([1, 2]))

# 矩陣相乘: tf.matmul
XW = tf.matmul(X, W)

Sum = XW + b

# 活化函數為 relu function
#y = tf.nn.relu(Sum)

# 活化函數為 sigmoid function
y = tf.nn.sigmoid(Sum)

# 執行計算圖
with tf.Session() as sess:
    # 初始化所有 tensorflow global 變數
    init = tf.global_variables_initializer()
    sess.run(init)
    
    # 執行一次取得三個變數
    (_XW, _Sum, _y) = sess.run((XW, Sum, y))
    
    print('XW=')
    print(_XW)
    print('-------------------------------')
    print('Sum=')
    print(_Sum)
    print('-------------------------------')
    print('y=')
    print(_y)

XW=
[[0.40094423 0.1794315 ]]
-------------------------------
Sum=
[[-0.24312049  0.5653076 ]]
-------------------------------
y=
[[0.4395175  0.63767976]]


#### 3. 用 placeholder 傳進輸入值，權重與偏權值以常態分佈的亂數初始化

In [7]:
# 建立計算圖 (二維張量)
# 定義 placeholder X; 第一個參數: placeholder 的資料型態，第二個參數: placeholder 矩陣的形狀
X = tf.placeholder('float', [None, 3])

W = tf.Variable(tf.random_normal([3, 2]))

b = tf.Variable(tf.random_normal([1, 2]))

# 矩陣相乘: tf.matmul
XW = tf.matmul(X, W)

Sum = XW + b

# 活化函數為 relu function
#y = tf.nn.relu(Sum)

# 活化函數為 sigmoid function
y = tf.nn.sigmoid(Sum)

# 執行計算圖
with tf.Session() as sess:
    # 初始化所有 tensorflow global 變數
    init = tf.global_variables_initializer()
    sess.run(init)
    
    # 建立 X_array
    X_array = np.array([[0.4, 0.1, 0.3]])
    
    # 執行一次取得三個變數; placeholder X 以 feed_dict 傳入 X_array
    (_XW, _Sum, _y) = sess.run((XW, Sum, y), feed_dict = {X: X_array})
    print('XW=')
    print(_XW)
    print('-------------------------------')
    print('Sum=')
    print(_Sum)
    print('-------------------------------')
    print('y=')
    print(_y)

XW=
[[0.16138643 0.52491915]]
-------------------------------
Sum=
[[0.7391137 2.0749063]]
-------------------------------
y=
[[0.67680204 0.8884402 ]]


#### 4. 以類神經網路的 "層 (Layer)" 為單位進行運算 (只顯示 Output)  

建立類神經網路的 "層" (Layer) 

In [8]:
# 定義 layer 函數
# inputs: 輸入二維陣列的 placeholder, input_dim: 輸入神經元的數量
# output_dim: 輸出神經元的數量, activation: 活化函數 (預設為 None)
def layer(inputs, input_dim, output_dim, activation = None):
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    
    XW = tf.matmul(inputs, W)
    Sum = XW + b

    if activation is None:
        outputs = Sum
    
    else:
        outputs = activation(Sum)
        
    return outputs

執行 3 層神經網路的運算

In [9]:
# 輸入層
X = tf.placeholder('float', [None, 3])

# 隱藏層
h = layer(inputs = X, input_dim = 3, output_dim = 2, activation = tf.nn.sigmoid)

# 輸出層
y = layer(inputs = h, input_dim = 2, output_dim = 1)

# 執行計算圖
with tf.Session() as sess:
    # 初始化所有 tensorflow global 變數
    init = tf.global_variables_initializer()
    sess.run(init)
    
    # 建立 X_array
    X_array = np.array([[0.4, 0.1, 0.3]])
    
    # 執行一次取得三個變數; placeholder X 以 feed_dict 傳入 X_array
    (layer_X, layer_h, layer_y) = sess.run((X, h, y), feed_dict = {X: X_array})
    print('Input layer X:')
    print(layer_X)
    print('-------------------------------')
    print('Hidden layer h:')
    print(layer_h)
    print('-------------------------------')
    print('Output layer y:')
    print(layer_y)

Input layer X:
[[0.4 0.1 0.3]]
-------------------------------
Hidden layer h:
[[0.90489554 0.7821733 ]]
-------------------------------
Output layer y:
[[-0.6456216]]


#### 5. 以類神經網路的 "層 (Layer)" 為單位進行運算 (顯示 Output、W、b)  

建立類神經網路的 "層" (Layer)

In [10]:
# 定義 layer 函數
# inputs: 輸入二維陣列的 placeholder, input_dim: 輸入神經元的數量
# output_dim: 輸出神經元的數量, activation: 活化函數 (預設為 None)
def layer(inputs, input_dim, output_dim, activation = None):
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    
    XW = tf.matmul(inputs, W)
    Sum = XW + b

    if activation is None:
        outputs = Sum
    
    else:
        outputs = activation(Sum)
        
    return outputs, W, b

執行 3 層神經網路的運算

In [11]:
# 輸入層
X = tf.placeholder('float', [None, 3])

# 隱藏層
h, W1, b1 = layer(inputs = X, input_dim = 3, output_dim = 2, activation = tf.nn.sigmoid)

# 輸出層
y, W2, b2 = layer(inputs = h, input_dim = 2, output_dim = 1)

# 執行計算圖
with tf.Session() as sess:
    # 初始化所有 tensorflow global 變數
    init = tf.global_variables_initializer()
    sess.run(init)
    
    # 建立 X_array
    X_array = np.array([[0.4, 0.1, 0.3]])
    
    # 執行一次取得 7 個變數; placeholder X 以 feed_dict 傳入 X_array
    (layer_X, layer_h, layer_y, _W1, _b1, _W2, _b2) = \
    sess.run((X, h, y, W1, b1, W2, b2), feed_dict = {X: X_array})
    
    print('Input layer X:')
    print(layer_X)
    print('-------------------------------')
    print('W1:')
    print(_W1)    
    print('-------------------------------')
    print('b1:')
    print(_b1)    
    print('-------------------------------')
    print('Hidden layer h:')
    print(layer_h)
    print('-------------------------------')
    print('W2:')
    print(_W2)    
    print('-------------------------------')
    print('b2:')
    print(_b2)    
    print('-------------------------------')
    print('Output layer y:')
    print(layer_y)

Input layer X:
[[0.4 0.1 0.3]]
-------------------------------
W1:
[[ 1.1064392   1.0536405 ]
 [-0.7296762  -0.69252974]
 [-0.75612456  0.3161065 ]]
-------------------------------
b1:
[[-0.75045925  1.2871991 ]]
-------------------------------
Hidden layer h:
[[0.35258666 0.8499532 ]]
-------------------------------
W2:
[[ 0.3820217]
 [-1.5300794]]
-------------------------------
b2:
[[1.4261199]]
-------------------------------
Output layer y:
[[0.26031983]]
